version: '3.8'

services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rOtRhIyfdoKYZOZyPaOyfEpmmwAHwOhE
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: spring-api
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.railway.internal:5432/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: rOtRhIyfdoKYZOZyPaOyfEpmmwAHwOhE

volumes:
  postgres-data:
